#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $USERDB with encrypted password '$USERDB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $USERDB;

    ALTER SCHEMA public OWNER TO $USERDB;

    CREATE EXTENSION pgcrypto;
    CREATE EXTENSION intarray;
    CREATE EXTENSION IF NOT EXISTS plpython3u;

    CREATE ROLE myadmin WITH SUPERUSER NOINHERIT;
    GRANT myadmin TO $USERDB;
EOSQL